apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  name: artifactory-backup
  labels:
    type: backup
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    path: /srv/nfs/artifactory-backup
    server: bastion.calpers.ca.gov
  persistentVolumeReclaimPolicy: Retain

