apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  name: artifactory-etc
  labels: 
    type: etc
   
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    path: /srv/nfs/artifactory-etc
    server: bastion.calpers.ca.gov
  persistentVolumeReclaimPolicy: Retain

