apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  name: artifactory-logs
  labels:
    type: logs
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    path: /srv/nfs/artifactory-logs
    server: bastion.calpers.ca.gov
