apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  name: artifactory-postgres
  labels: 
    type: postgres
   
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    path: /srv/nfs/artifactory-postgres
    server: bastion.calpers.ca.gov
  persistentVolumeReclaimPolicy: Retain

