apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  name: artifactory-var
  labels:
    type: var
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  nfs:
    path: /srv/nfs/artifactory-var
    server: bastion.calpers.ca.gov
  persistentVolumeReclaimPolicy: Retain
